### ISSUE TITLE
build: libkmod.h not found

### ISSUE THREAD

**Issue by ddiss** [open-iscsi/open-iscsi#146]
Current master fails to build on openSUSE 42.3:

```
> git log --pretty=oneline -1 |cat
c3d96cf3f3a53f0ec8f6617d46aecf59cdfdc496 Merge pull request #145 from gonzoleeman/fix-i586-build-warnings
> make
make -C libopeniscsiusr
make[1]: Entering directory 'open-iscsi/libopeniscsiusr'
cc -O2 -g -Wall -Werror -Wextra -fvisibility=hidden -fPIC   -c -o iface.o iface.c
iface.c:36:21: fatal error: libkmod.h: No such file or directory
 #include <libkmod.h>
```

With libkmod-devel installed, the header file is located at:
/usr/include/kmod-17/libkmod.h

The package contains a pkgconfig file (/usr/lib64/pkgconfig/libkmod.pc), which can be used to determine the correct include path and set CFLAGS+LDFLAGS accordingly:

`export CFLAGS=$(pkg-config --cflags libkmod libsystemd-daemon) LDFLAGS=$(pkg-config --libs libkmod libsystemd-daemon)`
-> note that I add libkmod **and** libsystemd-daemon to the pkg-config check, as "-lsystemd" also seems to be missing from the default linker flags.

**Comment by ddiss** [comment]
How about something like the following?
```
diff --git a/libopeniscsiusr/Makefile b/libopeniscsiusr/Makefile
index bf7c96c..4bec9a0 100644
--- a/libopeniscsiusr/Makefile
+++ b/libopeniscsiusr/Makefile
@@ -42,7 +42,9 @@ EXTRA_MAN_FILES = libopeniscsiusr.h.3
 OBJS = context.o misc.o session.o sysfs.o iface.o idbm.o node.o default.o
 
 CFLAGS ?= -O2 -g
-CFLAGS += -Wall -Werror -Wextra -fvisibility=hidden -fPIC
+CFLAGS += -Wall -Werror -Wextra -fvisibility=hidden -fPIC \
+         $(pkg-config --cflags libkmod)
+LDFLAGS += $(pkg-config --libs libkmod)
 
 LIBADD =
 
diff --git a/usr/Makefile b/usr/Makefile
index f9445ad..243e794 100644
--- a/usr/Makefile
+++ b/usr/Makefile
@@ -35,8 +35,10 @@ endif
 CFLAGS ?= -O2 -g
 WARNFLAGS ?= -Wall -Wstrict-prototypes
 CFLAGS += $(WARNFLAGS) -I../include -I. -D_GNU_SOURCE \
-         -I$(TOPDIR)/libopeniscsiusr
-ISCSI_LIB = -L$(TOPDIR)/libopeniscsiusr -lopeniscsiusr
+         -I$(TOPDIR)/libopeniscsiusr \
+         $(pkg-config --cflags libkmod libsystemd-daemon)
+ISCSI_LIB = -L$(TOPDIR)/libopeniscsiusr -lopeniscsiusr \
+           $(pkg-config --libs libkmod libsystemd-daemon)
 PROGRAMS = iscsid iscsiadm iscsistart
 
 # libc compat files
```
Is it reasonable to assume the presence of the pkg-config binary alongside corresponding libkmod.pc and libsystemd-daemon.pc files?

**Comment by gonzoleeman** [comment]
David, this forum is for open-iscsi in general, and your question is best directed at the SUSE version of open-iscsi, since nobody else here likely knows that "Factory" is. But as long as you're here ...

The reason that factory didn't compile on 42.3 was mostly that it wasn't needed on 42.3. Leap 42.3 has it's own open-iscsi package, which still does not even use libkmod (i.e. it execs "modprobe"). There is no need to update Leap 42.3.

But it's good that you pointed out to me that libkmod is indeed on Leap 42.3, but just in a different location.

I've merged a fix upstream that uses pkg-config for libsystemd and libkmod, as you suggest (thank you!). I think that's a great idea.

I'll also submit the changes to our factory build.

**Comment by gonzoleeman** [comment]
Closing this issue. Thanks again.
