### ISSUE TITLE
Build issue caused by commit 7635031

### ISSUE THREAD

**Issue by jkhasdev-ora** [open-iscsi/open-iscsi#274]
Recently, I rebased with upstream. Build on my machine stopped build and most likely caused by recent commit 7635031

open-iscsi]$ make
make -C libopeniscsiusr
make[1]: Entering directory '/home/opc/open-iscsi/libopeniscsiusr'
cc -O2 -g -Wall -Werror -Wextra -fvisibility=hidden -fPIC    -c -o idbm.o idbm.c
idbm.c: In function ‘_idbm_node_rec_link’:
idbm.c:999:3: error: ‘strncpy’ specified bound 65 equals destination size [-Werror=stringop-truncation]
   strncpy((*node).iface.name, iface_name, ISCSI_MAX_IFACE_LEN);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [<builtin>: idbm.o] Error 1
make[1]: Leaving directory '/home/opc/open-iscsi/libopeniscsiusr'
make: *** [Makefile:63: user] Error 2

**Comment by gonzoleeman** [comment]
Fixed by merged pull request #277
